### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by escalopa** [kodekulture/wordle-server#17]
- add zero log
- print error messages created by the handler
- print error messages created by the player conn
- colored logs

**Comment by lordvidex** [comment]
if the in-built log package will not show output in docker consoles? how can we guarantee that zerolog would show some output?

**Comment by escalopa** [comment]
- in-built log package do show messages in docker console, They just have low readability
- This feature is more like an improvement, But it doesn't add value to the app exp
- In general it might help on the long run for debugging

**Comment by lordvidex** [comment]
do you mean the prettyprinters or the json loggers?

The pretty printers will make it look beautiful on the console of the docker log, but for queriability, json format logs are the best, and I think we will have to choose one of this.

Unless, in some places, we use json loggers and in some cases we use pretty print loggers

**Comment by lordvidex** [comment]
This issue can be closed
